export default {
  login: "prudhvij15",
  id: 88441748,
  node_id: "MDQ6VXNlcjg4NDQxNzQ4",
  avatar_url: "https://avatars.githubusercontent.com/u/88441748?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/prudhvij15",
  html_url: "https://github.com/prudhvij15",
  followers_url: "https://api.github.com/users/prudhvij15/followers",
  following_url:
    "https://api.github.com/users/prudhvij15/following{/other_user}",
  gists_url: "https://api.github.com/users/prudhvij15/gists{/gist_id}",
  starred_url: "https://api.github.com/users/prudhvij15/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/prudhvij15/subscriptions",
  organizations_url: "https://api.github.com/users/prudhvij15/orgs",
  repos_url: "https://api.github.com/users/prudhvij15/repos",
  events_url: "https://api.github.com/users/prudhvij15/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/prudhvij15/received_events",
  type: "User",
  site_admin: false,
  name: "Prudhvi",
  company: "Coding Addict",
  blog: "https://prudhvij.com",
  location: "Overland Park , Kansas",
  email: null,
  hireable: null,
  bio: "Cofding Addickt",
  twitter_username: null,
  public_repos: 13,
  public_gists: 0,
  followers: 1,
  following: 2,
  created_at: "2021-08-04T13:29:40Z",
  updated_at: "2024-03-28T23:57:39Z",
};
